### ISSUE TITLE
Confusing version info

### ISSUE THREAD

**Issue by danfarnsy** [BobPalmer/CommunityCategoryKit#10]
@ihsoft 's most recent version has the version file 0.1.1.0 in the download (though titled 1.1.0 on the releases page). The previous one from @BobPalmer was 0.1.2.0, and before that, 0.1.1.0, making the current version a repeat.

**Comment by ihsoft** [comment]
Yeah, for some reason the version file hasn't been updated correctly.

**Comment by ihsoft** [comment]
Wait, no! The version is OK:
```
    "VERSION": {
        "BUILD": 0, 
        "MAJOR": 1, 
        "MINOR": 1, 
        "PATCH": 0
    }
```
You're probably confused by the order of the fields. The order is not important (they are sorted alphabetically in this case). The names are important, and they give us correct version `1.1.0` (`MAJOR.MINOR.PATCH`).
