### ISSUE TITLE
Containers category lacks un-inverted icon

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/CommunityCategoryKit#18]
Currently the Containers category icon is white; every other category has a dark unselected icon and a white selected icon. 

Suggestion: use the existing white icon for selectedIcon and create a color-inverted version for the normalIcon, such as the following...
![containers_n](https://cloud.githubusercontent.com/assets/9939641/24842044/57401214-1d5f-11e7-9577-687d00f79028.png)

**Comment by Nils277** [comment]
Will do so in the next release

**Comment by LouisB3** [comment]
Fixed in PR #29. Took me less than 3 years to change this icon!
