### ISSUE TITLE
Can we please have v5.1 released?

### ISSUE THREAD

**Issue by ihsoft** [BobPalmer/CommunityCategoryKit#32]
Due to outdated `.version` file CKAN doesn't recognize CCK as compatible with `1.9.1`, this results in marking all dependent mods as incompatible too. E.g. https://github.com/ihsoft/KAS/issues/293.

My last PR addresses this issue by removing the max version check.

**Comment by BobPalmer** [comment]
Yep - will work on it this weekend.

**Comment by ihsoft** [comment]
Gentle ping.

With your permission, I can do the release myself.

**Comment by BobPalmer** [comment]
Crazy weekend :)  Go for it!

**Comment by ihsoft** [comment]
Release is done: https://github.com/BobPalmer/CommunityCategoryKit/releases/tag/5.1.0.0
